---
- hosts: SE_Project
  become: yes
  tasks:
    - include_vars: git_token.yml

    - name: Install the gpg key for nodejs LTS
      shell: 'curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -'

    - name: Install the nodejs
      shell: 'sudo apt install -y nodejs'

    - name: Clone Github
      git:
        repo: https://{{git_key}}@github.ncsu.edu/csc510-s2022/CSC510-20.git
        dest: /project/
        clone: yes
        update: yes

    - name: Copy env file to remote server
      copy:
        src: .env
        dest: /project

    - name: Update apt repo and cache on all Ubuntu boxes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
        
    - name: Upgrade all packages on servers
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Install required packages
      apt:
        name:
          - wget
          - python3-psycopg2
          - acl
        state: latest

    - name: Set up Postgres 14 repo
      shell: |
        echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      args:
        warn: no

    - name: Install postgresql
      apt:
        name: postgresql-14
        update_cache: yes
      notify:
        - Enable Postgresql
